minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@types/*"
blockExoticSubdeps: true
overrides:
  postcss@<8.5.10: ">=8.5.10"
ignoredBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver
allowBuilds:
  msw: true
  sharp: true
  unrs-resolver: true
