minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@types/*"
blockExoticSubdeps: true
ignoredBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver
allowBuilds:
  msw: true
  sharp: true
  unrs-resolver: true
